name: cmac_env
channels:
  - conda-forge
dependencies:
  - python
  - arm_pyart
  - cartopy
  - coincbc
  - cmweather
  - cython
  - distributed
  - scikit-fuzzy
  - dask
  - wradlib
  - numpy
  - matplotlib
  - pyyaml
  - pip
