name: cmac_test_env
channels:
  - conda-forge
  - defaults
dependencies:
  - arm_pyart
  - cartopy
  - cmweather
  - coincbc
  - cython
  - dask
  - distributed
  - matplotlib
  - numpy
  - pytest
  - scikit-fuzzy
  - wradlib
  - pip
  - pip:
      - git+https://github.com/CSU-Radarmet/CSU_RadarTools.git
